// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

// esp-brookesia: changed
#include "ui.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_http_client.h"
#include "esp_heap_caps.h"
#include "esp_log.h"
#include "nvs.h"

extern const lv_font_t *ChineseFont_Get(void);

// esp-brookesia: changed
#if !defined(ESP_BROOKESIA_SQ1_4_1_LV8_3_11)
    #define _ui_screen_change(target, fademode, spd, delay, target_init) lv_scr_load_anim(*target, fademode, spd, delay, false)
#endif

///////////////////// VARIABLES ////////////////////
void upanim_Animation(lv_obj_t * TargetObject, int delay);
void hour_Animation(lv_obj_t * TargetObject, int delay);
void min_Animation(lv_obj_t * TargetObject, int delay);
void sec_Animation(lv_obj_t * TargetObject, int delay);
void scrolldot_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_SmartGadgetSplash
void ui_SmartGadgetSplash_screen_init(void);
void ui_event_SmartGadgetSplash(lv_event_t * e);
lv_obj_t * ui_SmartGadgetSplash;
lv_obj_t * ui_SmartGadgetSplash_Small_label_Demo;
lv_obj_t * ui_SmartGadgetSplash_Small_label_Smart_Gadget;
lv_obj_t * ui_SmartGadgetSplash_Image_SLS_Logo;


// SCREEN: ui_SmartGadgetClock
void ui_SmartGadgetClock_screen_init(void);
void ui_event_SmartGadgetClock(lv_event_t * e);
lv_obj_t * ui_SmartGadgetClock;
lv_obj_t * ui_SmartGadgetClock_Panel_Clock_Panel;
lv_obj_t * ui_SmartGadgetClock_Clock_dot_Dot1;
lv_obj_t * ui_SmartGadgetClock_Clock_dot_Dot2;
lv_obj_t * ui_SmartGadgetClock_Clock_dot_Dot3;
lv_obj_t * ui_SmartGadgetClock_Clock_dot_Dot4;
lv_obj_t * ui_SmartGadgetClock_Clock_dot_Dot5;
lv_obj_t * ui_SmartGadgetClock_Clock_dot_Dot6;
lv_obj_t * ui_SmartGadgetClock_Clock_dot_Dot7;
lv_obj_t * ui_SmartGadgetClock_Clock_dot_Dot8;
lv_obj_t * ui_SmartGadgetClock_Small_label_Clock_Number1;
lv_obj_t * ui_SmartGadgetClock_Small_label_Clock_Number2;
lv_obj_t * ui_SmartGadgetClock_Small_label_Clock_Number3;
lv_obj_t * ui_SmartGadgetClock_Small_label_Clock_Number4;
lv_obj_t * ui_SmartGadgetClock_Image_Min;
lv_obj_t * ui_SmartGadgetClock_Image_Hour;
lv_obj_t * ui_SmartGadgetClock_Image_Sec;
lv_obj_t * ui_SmartGadgetClock_Panel_Clock_Center;
lv_obj_t * ui_SmartGadgetClock_Label_Clock_Number;
lv_obj_t * ui_SmartGadgetClock_Small_label_Date;
lv_obj_t * ui_SmartGadgetClock_Scrolldots_Scrolldots;


// SCREEN: ui_SmartGadgetCall
void ui_SmartGadgetCall_screen_init(void);
void ui_event_SmartGadgetCall(lv_event_t * e);
lv_obj_t * ui_SmartGadgetCall;
lv_obj_t * ui_SmartGadgetCall_Small_label_Elena;
lv_obj_t * ui_SmartGadgetCall_Small_label_Incoming;
lv_obj_t * ui_SmartGadgetCall_Panel_Call_Incon1;
lv_obj_t * ui_SmartGadgetCall_Image_Phone1;
lv_obj_t * ui_SmartGadgetCall_Panel_Call_Incon2;
lv_obj_t * ui_SmartGadgetCall_Image_Phone2;
lv_obj_t * ui_SmartGadgetCall_Image_Avatar;
lv_obj_t * ui_SmartGadgetCall_Scrolldots_Scrolldots1;


// SCREEN: ui_SmartGadgetChat
void ui_SmartGadgetChat_screen_init(void);
void ui_event_SmartGadgetChat(lv_event_t * e);
lv_obj_t * ui_SmartGadgetChat;
lv_obj_t * ui_SmartGadgetChat_Panel_Chat_container;
lv_obj_t * ui_SmartGadgetChat_Small_label_Chat_date;
lv_obj_t * ui_SmartGadgetChat_Panel_C1;
lv_obj_t * ui_SmartGadgetChat_Panel_Chat_Panel1;
lv_obj_t * ui_SmartGadgetChat_Small_label_Chat1;
lv_obj_t * ui_SmartGadgetChat_Image_Chat_Icon1;
lv_obj_t * ui_SmartGadgetChat_Panel_C2;
lv_obj_t * ui_SmartGadgetChat_Panel_Chat_Panel2;
lv_obj_t * ui_SmartGadgetChat_Small_label_Chat2;
lv_obj_t * ui_SmartGadgetChat_Image_Chat_Icon2;
lv_obj_t * ui_SmartGadgetChat_Small_label_Delifered;
lv_obj_t * ui_SmartGadgetChat_Panel_C3;
lv_obj_t * ui_SmartGadgetChat_Panel_Chat_Panel3;
lv_obj_t * ui_SmartGadgetChat_Small_label_Chat3;
lv_obj_t * ui_SmartGadgetChat_Image_Chat_Icon3;
lv_obj_t * ui_SmartGadgetChat_Scrolldots_Scrolldots2;


// SCREEN: ui_SmartGadgetMusicPlayer
void ui_SmartGadgetMusicPlayer_screen_init(void);
void ui_event_SmartGadgetMusicPlayer(lv_event_t * e);
lv_obj_t * ui_SmartGadgetMusicPlayer;
lv_obj_t * ui_SmartGadgetMusicPlayer_Small_label_Music_Title;
lv_obj_t * ui_SmartGadgetMusicPlayer_Small_label_Author;
lv_obj_t * ui_SmartGadgetMusicPlayer_Panel_Play_btn;
lv_obj_t * ui_SmartGadgetMusicPlayer_Image_Play;
lv_obj_t * ui_SmartGadgetMusicPlayer_Image_Album;
lv_obj_t * ui_SmartGadgetMusicPlayer_Image_Backward;
lv_obj_t * ui_SmartGadgetMusicPlayer_Image_Forward;
lv_obj_t * ui_SmartGadgetMusicPlayer_Scrolldots_Scrolldots3;


// SCREEN: ui_SmartGadgetWeather
void ui_SmartGadgetWeather_screen_init(void);
void ui_event_SmartGadgetWeather(lv_event_t * e);
lv_obj_t * ui_SmartGadgetWeather;
lv_obj_t * ui_SmartGadgetWeather_Small_label_Pary_Cloud;
lv_obj_t * ui_SmartGadgetWeather_Small_label_New_York;
lv_obj_t * ui_SmartGadgetWeather_Image_Cloud;
lv_obj_t * ui_SmartGadgetWeather_Label_Celsius;
lv_obj_t * ui_SmartGadgetWeather_Panel_Weather_Icons;
lv_obj_t * ui_SmartGadgetWeather_Image_w1;
lv_obj_t * ui_SmartGadgetWeather_Image_w2;
lv_obj_t * ui_SmartGadgetWeather_Image_w3;
lv_obj_t * ui_SmartGadgetWeather_Small_label_W1_Num;
lv_obj_t * ui_SmartGadgetWeather_Small_label_W2_Num;
lv_obj_t * ui_SmartGadgetWeather_Small_label_W3_Num;
lv_obj_t * ui_SmartGadgetWeather_Scrolldots_Scrolldots4;


// SCREEN: ui_SmartGadgetAlarm
void ui_SmartGadgetAlarm_screen_init(void);
void ui_event_SmartGadgetAlarm(lv_event_t * e);
lv_obj_t * ui_SmartGadgetAlarm;
lv_obj_t * ui_SmartGadgetAlarm_Panel_Alarm_container;
lv_obj_t * ui_SmartGadgetAlarm_Small_label_Set_alarm;
lv_obj_t * ui_SmartGadgetAlarm_Alarm_comp_Alarm_Comp;
lv_obj_t * ui_SmartGadgetAlarm_Alarm_comp_Alarm_Comp1;
lv_obj_t * ui_SmartGadgetAlarm_Alarm_comp_Alarm_Comp2;
lv_obj_t * ui_SmartGadgetAlarm_Alarm_comp_Alarm_Comp3;
lv_obj_t * ui_SmartGadgetAlarm_Scrolldots_Scrolldots5;
const lv_img_dsc_t * ui_imgset_chatbox[1] = {&ui_img_chatbox2_png};
const lv_img_dsc_t * ui_imgset_weather_[3] = {&ui_img_weather_1_png, &ui_img_weather_2_png, &ui_img_weather_3_png};

///////////////////// ANIMATIONS ////////////////////
// esp-brookesia: changed

///////////////////// FUNCTIONS ////////////////////
static lv_obj_t *clock_location_label;
static lv_obj_t *clock_weather_label;
static lv_obj_t *clock_temperature_label;
static lv_timer_t *clock_refresh_timer;
static lv_timer_t *clock_weather_timer;
static bool clock_weather_fetch_running;

typedef struct {
    char time[16];
    char date[48];
    char timezone[40];
    char location[64];
    char condition[64];
    char temperature[24];
    char humidity[24];
    char wind[24];
} ClockWeatherResult;

static bool clock_server_time_valid;
static int clock_server_seconds;
static char clock_server_date[32];
static const char *CLOCK_TAG = "SquarelineClock";

typedef struct {
    char *data;
    size_t size;
} ClockWeatherBuffer;

static esp_err_t clock_weather_http_event(esp_http_client_event_t *event)
{
    if (event->event_id != HTTP_EVENT_ON_DATA || event->user_data == NULL) {
        return ESP_OK;
    }
    ClockWeatherBuffer *buffer = event->user_data;
    if (buffer->size + event->data_len >= 8191) {
        return ESP_FAIL;
    }
    memcpy(buffer->data + buffer->size, event->data, event->data_len);
    buffer->size += event->data_len;
    buffer->data[buffer->size] = '\0';
    return ESP_OK;
}

static bool clock_json_value(const char *json, const char *key, char *output, size_t output_size)
{
    char pattern[48];
    snprintf(pattern, sizeof(pattern), "\"%s\"", key);
    const char *key_start = strstr(json, pattern);
    if (key_start == NULL) return false;
    const char *colon = strchr(key_start + strlen(pattern), ':');
    if (colon == NULL) return false;
    const char *value = colon + 1;
    while (*value == ' ' || *value == '\t') value++;
    if (*value == '"') {
        value++;
        const char *end = strchr(value, '"');
        if (end == NULL) return false;
        size_t length = (size_t)(end - value);
        if (length >= output_size) length = output_size - 1;
        memcpy(output, value, length);
        output[length] = '\0';
        return true;
    }
    char *end = NULL;
    double number = strtod(value, &end);
    if (end == value) return false;
    snprintf(output, output_size, "%.1f", number);
    return true;
}

static bool clock_load_content_url(char *url, size_t url_size)
{
    nvs_handle_t handle;
    if (nvs_open("secretary", NVS_READONLY, &handle) != ESP_OK) return false;
    size_t required = url_size;
    esp_err_t result = nvs_get_str(handle, "content_url", url, &required);
    nvs_close(handle);
    return result == ESP_OK && url[0] != '\0';
}

static bool clock_service_base_url(char *url, size_t url_size)
{
    if (!clock_load_content_url(url, url_size)) return false;
    char *query = strchr(url, '?');
    if (query != NULL) *query = '\0';
    char *scheme = strstr(url, "://");
    char *api = scheme == NULL ? NULL : strstr(scheme + 3, "/api/");
    if (api != NULL) *api = '\0';
    size_t length = strlen(url);
    while (length > 0 && url[length - 1] == '/') url[--length] = '\0';
    return length > 0;
}

static bool clock_http_get(const char *url, char *response, size_t response_size)
{
    if (url == NULL || response == NULL || response_size < 2) return false;
    response[0] = '\0';
    ClockWeatherBuffer buffer = {response, 0};
    esp_http_client_config_t config = {};
    config.url = url;
    config.timeout_ms = 15000;
    config.event_handler = clock_weather_http_event;
    config.user_data = &buffer;
    esp_http_client_handle_t client = esp_http_client_init(&config);
    if (client == NULL) {
        ESP_LOGE(CLOCK_TAG, "HTTP init failed for %s", url);
        return false;
    }
    esp_err_t error = esp_http_client_perform(client);
    int status = esp_http_client_get_status_code(client);
    esp_http_client_cleanup(client);
    bool success = error == ESP_OK && status >= 200 && status < 300 && buffer.size < response_size;
    ESP_LOGI(CLOCK_TAG, "GET %s -> error=%s status=%d bytes=%u",
             url, esp_err_to_name(error), status, (unsigned)buffer.size);
    return success;
}

static void clock_ascii_date(const char *date, char *output, size_t output_size)
{
    int year = 0, month = 0, day = 0;
    if (date != NULL && sscanf(date, "%d年%d月%d日", &year, &month, &day) == 3) {
        const char *weekday = "";
        if (strstr(date, "星期一")) weekday = " Mon";
        else if (strstr(date, "星期二")) weekday = " Tue";
        else if (strstr(date, "星期三")) weekday = " Wed";
        else if (strstr(date, "星期四")) weekday = " Thu";
        else if (strstr(date, "星期五")) weekday = " Fri";
        else if (strstr(date, "星期六")) weekday = " Sat";
        else if (strstr(date, "星期日") || strstr(date, "星期天")) weekday = " Sun";
        snprintf(output, output_size, "%04d-%02d-%02d%s", year, month, day, weekday);
    } else {
        snprintf(output, output_size, "%s", date == NULL ? "Date unavailable" : date);
    }
}

static void clock_weather_apply(void *arg)
{
    ClockWeatherResult *weather = arg;
    if (weather == NULL) return;
    const lv_font_t *chinese_font = ChineseFont_Get();
    if (chinese_font != NULL) {
        lv_obj_set_style_text_font(ui_SmartGadgetClock_Small_label_Date, chinese_font, 0);
        lv_obj_set_style_text_font(clock_location_label, chinese_font, 0);
        lv_obj_set_style_text_font(clock_weather_label, chinese_font, 0);
        lv_obj_set_style_text_font(clock_temperature_label, chinese_font, 0);
    }
    if (clock_location_label != NULL && weather->location[0] != '\0') {
        lv_label_set_text(clock_location_label, weather->location);
    }
    if (clock_weather_label != NULL && weather->condition[0] != '\0') {
        lv_label_set_text(clock_weather_label, weather->condition);
    }
    if (clock_temperature_label != NULL) {
        char details[96];
        snprintf(details, sizeof(details), "%s C   Humidity %s%%   Wind %s",
                 weather->temperature[0] ? weather->temperature : "--",
                 weather->humidity[0] ? weather->humidity : "--",
                 weather->wind[0] ? weather->wind : "--");
        lv_label_set_text(clock_temperature_label, details);
    }
    if (weather->date[0] != '\0') {
        clock_ascii_date(weather->date, clock_server_date, sizeof(clock_server_date));
        lv_label_set_text(ui_SmartGadgetClock_Small_label_Date, clock_server_date);
    }
    free(weather);
}

static void clock_weather_fetch_task(void *)
{
    char base[256] = {};
    char endpoint[320] = {};
    char *response = heap_caps_calloc(1, 8192, MALLOC_CAP_8BIT);
    ClockWeatherResult *weather = calloc(1, sizeof(ClockWeatherResult));
    if (response != NULL && weather != NULL && clock_service_base_url(base, sizeof(base))) {
        ESP_LOGI(CLOCK_TAG, "Content URL base: %s", base);
        snprintf(endpoint, sizeof(endpoint), "%s/api/clock", base);
        if (clock_http_get(endpoint, response, 8192)) {
            clock_json_value(response, "time", weather->time, sizeof(weather->time));
            clock_json_value(response, "date", weather->date, sizeof(weather->date));
            clock_json_value(response, "timezone", weather->timezone, sizeof(weather->timezone));
            int hour = 0, minute = 0, second = 0;
            if (sscanf(weather->time, "%d:%d:%d", &hour, &minute, &second) == 3) {
                clock_server_seconds = hour * 3600 + minute * 60 + second;
                clock_server_time_valid = true;
            }

        }
        snprintf(endpoint, sizeof(endpoint), "%s/api/location", base);
        if (clock_http_get(endpoint, response, 8192)) {
            clock_json_value(response, "message", weather->location, sizeof(weather->location));
            if (weather->location[0] == '\0') clock_json_value(response, "city", weather->location, sizeof(weather->location));
        }

        snprintf(endpoint, sizeof(endpoint), "%s/api/weather", base);
        if (clock_http_get(endpoint, response, 8192)) {
            clock_json_value(response, "desc", weather->condition, sizeof(weather->condition));
            clock_json_value(response, "temp", weather->temperature, sizeof(weather->temperature));
            clock_json_value(response, "humidity", weather->humidity, sizeof(weather->humidity));
            clock_json_value(response, "wind", weather->wind, sizeof(weather->wind));
        }
        clock_ascii_date(weather->date, clock_server_date, sizeof(clock_server_date));
        ESP_LOGI(CLOCK_TAG, "Parsed location=%s weather=%s temp=%s humidity=%s wind=%s",
                 weather->location, weather->condition, weather->temperature,
                 weather->humidity, weather->wind);
        lv_async_call(clock_weather_apply, weather);
        weather = NULL;
    } else {
        ESP_LOGW(CLOCK_TAG, "Content URL unavailable or allocation failed");
    }
    free(response);
    free(weather);
    clock_weather_fetch_running = false;
    vTaskDelete(NULL);
}

static void clock_weather_timer_cb(lv_timer_t *timer)
{
    (void)timer;
    if (!clock_weather_fetch_running) {
        clock_weather_fetch_running = true;
        if (xTaskCreate(clock_weather_fetch_task, "clock-weather", 6144, NULL, 1, NULL) != pdPASS) {
            clock_weather_fetch_running = false;
        }
    }
}

static void clock_refresh_timer_cb(lv_timer_t *timer)
{
    (void)timer;
    time_t now = time(NULL);
    struct tm time_info = {};
    localtime_r(&now, &time_info);

    if (clock_server_time_valid) {
        int seconds = clock_server_seconds++ % (24 * 60 * 60);
        time_info.tm_hour = seconds / 3600;
        time_info.tm_min = (seconds / 60) % 60;
        time_info.tm_sec = seconds % 60;
    }

    char time_text[8];
    char date_text[32];
    strftime(time_text, sizeof(time_text), "%H:%M", &time_info);
    if (clock_server_time_valid && clock_server_date[0] != '\0') {
        snprintf(date_text, sizeof(date_text), "%s", clock_server_date);
    } else {
        strftime(date_text, sizeof(date_text), "%a %d %b %Y", &time_info);
    }
    lv_label_set_text(ui_SmartGadgetClock_Label_Clock_Number, time_text);
    lv_label_set_text(ui_SmartGadgetClock_Small_label_Date, date_text);

    lv_img_set_angle(ui_SmartGadgetClock_Image_Hour,
                     (time_info.tm_hour % 12) * 300 + time_info.tm_min * 5);
    lv_img_set_angle(ui_SmartGadgetClock_Image_Min, time_info.tm_min * 60);
    lv_img_set_angle(ui_SmartGadgetClock_Image_Sec, time_info.tm_sec * 60);
}

static void clock_create_info_panel(void)
{
    if (clock_location_label != NULL) {
        return;
    }

    // Place the enlarged clock above its date label and the weather panel.
    lv_obj_set_y(ui_SmartGadgetClock_Panel_Clock_Panel, -190);
    lv_obj_set_style_transform_pivot_x(ui_SmartGadgetClock_Panel_Clock_Panel, 90, 0);
    lv_obj_set_style_transform_pivot_y(ui_SmartGadgetClock_Panel_Clock_Panel, 90, 0);
    lv_obj_set_style_transform_zoom(ui_SmartGadgetClock_Panel_Clock_Panel, 512, 0);
    lv_obj_add_flag(ui_SmartGadgetClock_Label_Clock_Number, LV_OBJ_FLAG_HIDDEN);

    lv_obj_set_y(ui_SmartGadgetClock_Small_label_Date, 405);
    lv_obj_set_style_text_font(ui_SmartGadgetClock_Small_label_Date, &lv_font_montserrat_22, 0);

    lv_obj_t *panel = lv_obj_create(ui_SmartGadgetClock);
    lv_obj_set_size(panel, 420, 165);
    lv_obj_align(panel, LV_ALIGN_BOTTOM_MID, 0, -28);
    lv_obj_set_style_bg_color(panel, lv_color_hex(0xFFFFFF), 0);
    lv_obj_set_style_bg_opa(panel, LV_OPA_80, 0);
    lv_obj_set_style_border_color(panel, lv_color_hex(0xB8C5E8), 0);
    lv_obj_set_style_border_width(panel, 1, 0);
    lv_obj_set_style_radius(panel, 12, 0);
    lv_obj_clear_flag(panel, LV_OBJ_FLAG_SCROLLABLE);

    clock_location_label = lv_label_create(panel);
    lv_label_set_text(clock_location_label, "Location unavailable");
    lv_obj_set_style_text_font(clock_location_label, &lv_font_montserrat_24, 0);
    lv_obj_set_style_text_color(clock_location_label, lv_color_hex(0x293062), 0);
    lv_obj_align(clock_location_label, LV_ALIGN_TOP_MID, 0, 12);

    clock_weather_label = lv_label_create(panel);
    lv_label_set_text(clock_weather_label, "Weather unavailable");
    lv_obj_set_style_text_font(clock_weather_label, &lv_font_montserrat_22, 0);
    lv_obj_set_style_text_color(clock_weather_label, lv_color_hex(0x293062), 0);
    lv_obj_align(clock_weather_label, LV_ALIGN_TOP_MID, 0, 52);

    clock_temperature_label = lv_label_create(panel);
    lv_label_set_text(clock_temperature_label, "-- C   Humidity --%   Wind --");
    lv_obj_set_style_text_font(clock_temperature_label, &lv_font_montserrat_22, 0);
    lv_obj_set_style_text_color(clock_temperature_label, lv_color_hex(0x59688F), 0);
    lv_obj_align(clock_temperature_label, LV_ALIGN_TOP_MID, 0, 100);
}

void ui_event_SmartGadgetSplash(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        upanim_Animation(ui_SmartGadgetSplash_Image_SLS_Logo, 100);
        upanim_Animation(ui_SmartGadgetSplash_Small_label_Smart_Gadget, 200);
        upanim_Animation(ui_SmartGadgetSplash_Small_label_Demo, 300);
        _ui_screen_change(&ui_SmartGadgetClock, LV_SCR_LOAD_ANIM_FADE_ON, 200, 1400, &ui_SmartGadgetClock_screen_init);
    }
}
void ui_event_SmartGadgetClock(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        upanim_Animation(ui_SmartGadgetClock_Label_Clock_Number, 300);
        scrolldot_Animation(ui_SmartGadgetClock_Scrolldots_Scrolldots, 0);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        clock_create_info_panel();
        if (clock_refresh_timer == NULL) {
            clock_refresh_timer = lv_timer_create(clock_refresh_timer_cb, 1000, NULL);
        }
        if (clock_weather_timer == NULL) {
            clock_weather_timer = lv_timer_create(clock_weather_timer_cb, 30 * 60 * 1000, NULL);
        }
        clock_refresh_timer_cb(clock_refresh_timer);
        clock_weather_timer_cb(clock_weather_timer);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SmartGadgetCall, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_SmartGadgetCall_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SmartGadgetAlarm, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SmartGadgetAlarm_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        hour_Animation(ui_SmartGadgetClock_Image_Hour, 200);
        min_Animation(ui_SmartGadgetClock_Image_Min, 400);
    }
}
void ui_event_SmartGadgetCall(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        upanim_Animation(ui_SmartGadgetCall_Image_Avatar, 100);
        upanim_Animation(ui_SmartGadgetCall_Small_label_Elena, 200);
        upanim_Animation(ui_SmartGadgetCall_Small_label_Incoming, 300);
        upanim_Animation(ui_SmartGadgetCall_Panel_Call_Incon1, 200);
        upanim_Animation(ui_SmartGadgetCall_Panel_Call_Incon2, 300);
        scrolldot_Animation(ui_SmartGadgetCall_Scrolldots_Scrolldots1, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SmartGadgetChat, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SmartGadgetChat_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SmartGadgetClock, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SmartGadgetClock_screen_init);
    }
}
void ui_event_SmartGadgetChat(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        upanim_Animation(ui_SmartGadgetChat_Small_label_Chat_date, 100);
        upanim_Animation(ui_SmartGadgetChat_Panel_C1, 200);
        upanim_Animation(ui_SmartGadgetChat_Panel_C2, 300);
        upanim_Animation(ui_SmartGadgetChat_Panel_C3, 400);
        scrolldot_Animation(ui_SmartGadgetChat_Scrolldots_Scrolldots2, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SmartGadgetCall, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SmartGadgetCall_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SmartGadgetMusicPlayer, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SmartGadgetMusicPlayer_screen_init);
    }
}
void ui_event_SmartGadgetMusicPlayer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        upanim_Animation(ui_SmartGadgetMusicPlayer_Image_Album, 100);
        upanim_Animation(ui_SmartGadgetMusicPlayer_Small_label_Music_Title, 200);
        upanim_Animation(ui_SmartGadgetMusicPlayer_Small_label_Author, 300);
        upanim_Animation(ui_SmartGadgetMusicPlayer_Panel_Play_btn, 200);
        upanim_Animation(ui_SmartGadgetMusicPlayer_Image_Forward, 300);
        upanim_Animation(ui_SmartGadgetMusicPlayer_Image_Backward, 400);
        scrolldot_Animation(ui_SmartGadgetMusicPlayer_Scrolldots_Scrolldots3, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SmartGadgetChat, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SmartGadgetChat_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SmartGadgetWeather, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SmartGadgetWeather_screen_init);
    }
}
void ui_event_SmartGadgetWeather(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        upanim_Animation(ui_SmartGadgetWeather_Image_Cloud, 100);
        upanim_Animation(ui_SmartGadgetWeather_Small_label_Pary_Cloud, 200);
        upanim_Animation(ui_SmartGadgetWeather_Label_Celsius, 300);
        upanim_Animation(ui_SmartGadgetWeather_Small_label_New_York, 400);
        upanim_Animation(ui_SmartGadgetWeather_Panel_Weather_Icons, 300);
        scrolldot_Animation(ui_SmartGadgetWeather_Scrolldots_Scrolldots4, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SmartGadgetMusicPlayer, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SmartGadgetMusicPlayer_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SmartGadgetAlarm, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SmartGadgetAlarm_screen_init);
    }
}
void ui_event_SmartGadgetAlarm(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        upanim_Animation(ui_SmartGadgetAlarm_Small_label_Set_alarm, 100);
        upanim_Animation(ui_SmartGadgetAlarm_Alarm_comp_Alarm_Comp, 200);
        upanim_Animation(ui_SmartGadgetAlarm_Alarm_comp_Alarm_Comp1, 300);
        upanim_Animation(ui_SmartGadgetAlarm_Alarm_comp_Alarm_Comp2, 400);
        upanim_Animation(ui_SmartGadgetAlarm_Alarm_comp_Alarm_Comp3, 500);
        scrolldot_Animation(ui_SmartGadgetAlarm_Scrolldots_Scrolldots5, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SmartGadgetWeather, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SmartGadgetWeather_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SmartGadgetClock, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SmartGadgetClock_screen_init);
    }
}
void ui_event_Startevents____initial_actions0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        sec_Animation(ui_SmartGadgetClock_Image_Sec, 0);
    }
}

///////////////////// SCREENS ////////////////////

// esp-brookesia: changed
void phone_app_squareline_ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_basic_init(dispp);
    lv_disp_set_theme(dispp, theme);
    ui_SmartGadgetSplash_screen_init();
    ui_SmartGadgetClock_screen_init();
    ui_SmartGadgetCall_screen_init();
    ui_SmartGadgetChat_screen_init();
    ui_SmartGadgetMusicPlayer_screen_init();
    ui_SmartGadgetWeather_screen_init();
    ui_SmartGadgetAlarm_screen_init();
    lv_disp_load_scr(ui_SmartGadgetSplash);
}
